### ISSUE TITLE
Port to run on  PyPy

### ISSUE THREAD

**Issue by icemac** [zopefoundation/AccessControl#37]
Currently there are errors like:

```
Error in test test_SetPermissionDefault (AccessControl.tests.testClassSecurityInfo.ClassSecurityInfoTests)
Traceback (most recent call last):
  File "/opt/local/lib/pypy/lib-python/2.7/unittest/case.py", line 329, in run
    testMethod()
  File ".../AccessControl/src/AccessControl/tests/testClassSecurityInfo.py", line 97, in test_SetPermissionDefault
    self.assertEqual(object.public__roles__, None)
  File ".../AccessControl/.tox/pypy/site-packages/ExtensionClass/__init__.py", line 254, in Base_getattro
    type(self).__name__, name)
AttributeError: ("'%.50s' object has not attribute '%s'", 'Test', 'public__roles__')
```

**Comment by icemac** [comment]
As `RestrictedPython` and many other Zope dependencies at least currently do not support PyPy and some probably never will, there is no pressure for this issue.
