### ISSUE TITLE
allow_class(StringIO) fails in python 3

### ISSUE THREAD

**Issue by pbauer** [zopefoundation/AccessControl#58]
During startup of Plopmne with python3: 

```
Traceback (most recent call last):
  File "./bin/wsgi.py", line 242, in <module>
    wsgiapp = make_wsgi_app({}, '/Users/pbauer/workspace/coredev_py3/parts/wsgi.py/etc/zope.conf')
  File "/Users/pbauer/workspace/coredev_py3/src/Zope/src/Zope2/Startup/run.py", line 67, in make_wsgi_app
    starter.prepare()
  File "/Users/pbauer/workspace/coredev_py3/src/Zope/src/Zope2/Startup/starter.py", line 38, in prepare
    self.startZope()
  File "/Users/pbauer/workspace/coredev_py3/src/Zope/src/Zope2/Startup/starter.py", line 105, in startZope
    Zope2.startup_wsgi()
  File "/Users/pbauer/workspace/coredev_py3/src/Zope/src/Zope2/__init__.py", line 49, in startup_wsgi
    _startup()
  File "/Users/pbauer/workspace/coredev_py3/src/Zope/src/Zope2/App/startup.py", line 152, in startup
    OFS.Application.initialize(application)
  File "/Users/pbauer/workspace/coredev_py3/src/Zope/src/OFS/Application.py", line 199, in initialize
    initializer.initialize()
  File "/Users/pbauer/workspace/coredev_py3/src/Zope/src/OFS/Application.py", line 221, in initialize
    self.install_products()
  File "/Users/pbauer/workspace/coredev_py3/src/Zope/src/OFS/Application.py", line 302, in install_products
    return install_products()
  File "/Users/pbauer/workspace/coredev_py3/src/Zope/src/OFS/Application.py", line 327, in install_products
    folder_permissions)
  File "/Users/pbauer/workspace/coredev_py3/src/Zope/src/OFS/Application.py", line 431, in install_product
    initmethod(context)
  File "/Users/pbauer/workspace/coredev_py3/src/Products.CMFPlone/Products/CMFPlone/__init__.py", line 73, in initialize
    allow_class(StringIO)
  File "/Users/pbauer/.cache/buildout/eggs/AccessControl-4.0b3-py3.6-macosx-10.12-x86_64.egg/AccessControl/SecurityInfo.py", line 364, in allow_class
    Class._security = sec = ClassSecurityInfo()
TypeError: can't set attributes of built-in/extension type '_io.StringIO'
```

**Comment by icemac** [comment]
@pbauer What is your current workaround for this issue in Plone? Did you remove the `allow_class(StringIO)` from the Plone code?

I think it is not obsolete, it allow to use `StringIO` in PythonScripts in the ZODB (TTW). I do not know if this is needed in Plone.

**Comment by icemac** [comment]
@pbauer Sorry for asking before looking into your commit. I think this is the way to go if `StringIO` is not needed in Plone in other places. So, can we close this issue?

**Comment by pbauer** [comment]
I'm not sure if that is need. It does not seem to break any tests though.
